[build]
  # Command to build your Vite project
  command = "npm run build"
  
  # Directory to publish after the build
  publish = "dist"

[dev]
  # Point Netlify Dev to the Vite dev server
  framework = "vite"

[[redirects]]
  # Redirect API requests to your backend server on Vercel
  from = "/api/fitass/*"
  to = "https://fitass-server.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  # Redirect all other routes to index.html for SPA support
  from = "/*"
  to = "/index.html"
  status = 200
